version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "17:00"
      timezone: America/Los_Angeles
    assignees:
      - dev01d

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
      time: "17:00"
      timezone: America/Los_Angeles
    assignees:
      - dev01d

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "17:30"
      timezone: America/Los_Angeles
    assignees:
      - dev01d
