FROM node:lts-buster-slim
LABEL maintainer="Jason Behnke <contact@jasonbehnke.io>"
#
RUN mkdir /opt/app && chown node:node /opt/app
WORKDIR /opt/app
#
USER node
#
COPY ./src ./src
COPY ./public ./public
COPY package.json yarn.lock ./
COPY docker-entrypoint.sh /usr/local/bin/
#
RUN yarn install
#
ENTRYPOINT ["docker-entrypoint.sh"]
#
EXPOSE 3000
#
CMD [ "yarn", "start"]